POST http://localhost:5001/send-email HTTP/1.1
content-type: application/json

{
    "to": "corsnix786@gmail.com",
    "subject": "need help",
    "text": "Hi there I am Owais and if you need anything, let me know",
    "first":"Muhammad",
    "last":"Owais"
}